### ISSUE TITLE
[Parent] - Kedro VSCode IDE Roadmap

### ISSUE THREAD

**Issue by noklam** [kedro-org/vscode-kedro#58]
Tracker:
- [x] https://github.com/kedro-org/kedro-viz/pull/1992 setup the path to use Kedro-viz as a React Component, this gives us the opportunity to integrate viz in VSCode directly via Webview

**0.2.0(pre-release) &0.2.2**
Release after next kedro viz (1st week of September, as rely on both the main npm/python `kedro-viz`)

- [x] https://github.com/kedro-org/kedro-viz/issues/1968
- [x] https://github.com/kedro-org/vscode-kedro/issues/72
- [x] #68
- [x] https://github.com/kedro-org/vscode-kedro/issues/62
- [x] https://github.com/kedro-org/vscode-kedro/pull/65
- [x] https://github.com/kedro-org/kedro-viz/issues/2022
- [x] #56 
- [x] https://github.com/kedro-org/kedro-viz/issues/2024
- [x] https://github.com/kedro-org/vscode-kedro/pull/70
- [x] https://github.com/kedro-org/kedro-viz/pull/2049
- [x] https://github.com/kedro-org/kedro-viz/pull/2060
- [x] https://github.com/kedro-org/vscode-kedro/issues/90
- [x] https://github.com/kedro-org/vscode-kedro/pull/92
- [x] https://github.com/kedro-org/vscode-kedro/pull/104
- [x] #73
- [x] #67 
- [x] https://github.com/kedro-org/vscode-kedro/pull/99
- [x] #71
- [x] https://github.com/kedro-org/vscode-kedro/pull/93

**0.2.3 (bug fix release)**
- [x] https://github.com/kedro-org/vscode-kedro/issues/53
- [x] #102 
- [x] #77 
- [x] https://github.com/kedro-org/vscode-kedro/issues/123
- [x] #78
- [x] #126 

**0.3.0**
- Use symbol / cache to improve performance
- [ ] #60
- [x] #5

Not scheduled (wait a bit for telemetry/issues coming in):
- [ ] https://github.com/kedro-org/vscode-kedro/issues/8
- [ ] https://github.com/kedro-org/vscode-kedro/issues/10
- [x] #64
- [ ] #69

**Comment by noklam** [comment]
2024-08-21 Kedro Extension / Viz integration

## Flowchart Rendering
The non-deterministic rendenring of flowchart creates challenge when used with auto-reload in VSCode. Due to the high frequency of reloading, the node position will flip often for small/medium size pipeline and create an awkward UX.

- @rashidakanchwala mention that the rendering part is done in some old code and is not easy to control because the algorithm has some randomness (as I understand it's an optimisation algorithm)
- @merelcht challenge if it's actually required to have auto-reload

Temporary solution:
- Disable autoreload, ask user to re-run the `Run viz` command instead.
  - Could have a button, but probably not worth it for temporary solution, we just keep it simple and document the behavior clearly.

Other options discussed:
- Have an option to turn off autoreload if user want.
- Reduce the autoreload frequency, maybe every 30s or only reload when there are new changes. This can reduce the issue but wouldn't solve the problem completely.

## Telemetry
- @Huongg mentioned it will be useful to differentiate telemetry between a browser and extension.
- @DimedS comment that maybe we need to have a look at `kedro-viz` telemetry consent flow, it should respect to the changes we made for `kedro-telemetry` lately, for example the environment variable `DO_NOT_TRACK`.
- @rashidakanchwala mentioned that she wasn't sure if the HEAP event will be sent properly in the React component

Follow up:
- Check with how consent flow works for `kedro-viz`
- How to identify unique user/project in UI (Is it the same as kedro-telemetry?)
- Check if the flowchart React component send HEAP event

**Comment by astrojuanlu** [comment]
Most of these have been done and 0.3 is out soon! We'll revisit the roadmap at another point
